apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-system

resources:
  - ../../base

patchesStrategicMerge:
  - replicas-patch.yaml
  - resources-patch.yaml

images:
  - name: api-gateway
    newName: inventory-system/api-gateway
    newTag: dev
  - name: auth-service
    newName: inventory-system/auth-service
    newTag: dev
  - name: inventory-service
    newName: inventory-system/inventory-service
    newTag: dev