apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: inventory-system
spec:
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: inventory-system
spec:
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: inventory-system
spec:
  template:
    spec:
      containers:
      - name: inventory-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: inventory-system
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: inventory-system
spec:
  template:
    spec:
      containers:
      - name: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"