{
 "title": "Inventory Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"inventory-service\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Response Time" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"inventory-service\"}[1m]) / rate(http_server_requests_seconds_count{application=\"inventory-service\"}[1m])",
     "legendFormat": "{{method}} {{uri}} {{status}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"inventory-service\", area=\"heap\"}) / sum(jvm_memory_max_bytes{application=\"inventory-service\", area=\"heap\"}) * 100"
    }
   ]
  }
 ]
}