apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inventory-system

resources:
  - ../../base

images:
  - name: api-gateway
    newName: inventory-system/api-gateway
    newTag: prod
  - name: auth-service
    newName: inventory-system/auth-service
    newTag: prod
  - name: inventory-service
    newName: inventory-system/inventory-service
    newTag: prod